name: mag_torch
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.13
  - aiosignal=1.3.2
  - apptools=5.3.1
  - blas=1.0
  - blosc=1.21.6
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.6.15
  - cairo=1.18.4
  - configobj=5.0.9
  - curl=8.14.1
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - double-conversion=3.3.1
  - eigen=3.4.0
  - envisage=7.0.4
  - expat=2.7.0
  - faiss-cpu=1.11.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.13.3
  - frozenlist=1.6.0
  - gettext=0.24.1
  - gettext-tools=0.24.1
  - gl2ps=1.4.2
  - glew=2.1.0
  - glib=2.84.2
  - glib-tools=2.84.2
  - graphite2=1.3.14
  - gst-plugins-base=1.24.11
  - gstreamer=1.24.11
  - h2=4.2.0
  - harfbuzz=11.2.1
  - hdf4=4.2.15
  - hdf5=1.14.6
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - importlib_resources=6.5.2
  - jsoncpp=1.9.6
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libaec=1.1.4
  - libasprintf=0.24.1
  - libasprintf-devel=0.24.1
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libclang=20.1.7
  - libclang-cpp17=17.0.6
  - libclang-cpp18.1=18.1.8
  - libclang13=20.1.7
  - libcurl=8.14.1
  - libcxx=20.1.7
  - libdeflate=1.24
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.7.0
  - libfaiss=1.11.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgettextpo=0.24.1
  - libgettextpo-devel=0.24.1
  - libgfortran=5.0.0
  - libgfortran5=14.2.0
  - libglib=2.84.2
  - libhwloc=2.11.2
  - libiconv=1.18
  - libintl=0.24.1
  - libintl-devel=0.24.1
  - libjpeg-turbo=3.1.0
  - libllvm15=15.0.7
  - libllvm17=17.0.6
  - libllvm18=18.1.8
  - libllvm20=20.1.7
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnetcdf=4.9.2
  - libnghttp2=1.64.0
  - libntlm=1.8
  - libogg=1.3.5
  - libopenblas=0.3.29
  - libopus=1.5.2
  - libpng=1.6.49
  - libpq=17.5
  - libsqlite=3.50.2
  - libssh2=1.11.1
  - libtheora=1.1.1
  - libtiff=4.7.0
  - libvorbis=1.3.7
  - libwebp-base=1.5.0
  - libxcb=1.15
  - libxml2=2.13.8
  - libzip=1.11.2
  - libzlib=1.3.1
  - llvm-openmp=20.1.7
  - loguru=0.7.3
  - lz4-c=1.10.0
  - matplotlib-base=3.10.1
  - mayavi=4.8.3
  - msgpack-python=1.1.1
  - multidict=6.6.0
  - munkres=1.1.4
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - ncurses=6.5
  - nlohmann_json=3.12.0
  - nomkl=3.0
  - nspr=4.36
  - nss=3.113
  - openblas=0.3.29
  - openblas-devel=0.3.29
  - openjpeg=2.5.3
  - openldap=2.6.10
  - openssl=3.5.0
  - pcre2=10.45
  - pillow=10.3.0
  - pip=24.0
  - pixman=0.46.2
  - ply=3.11
  - pooch=1.8.2
  - proj=9.6.2
  - propcache=0.3.1
  - pthread-stubs=0.4
  - pugixml=1.15
  - pycparser=2.22
  - pyface=8.0.0
  - pygments=2.19.2
  - pyqt=5.15.11
  - pysocks=1.7.1
  - python=3.11.8
  - python-dateutil=2.9.0.post0
  - python_abi=3.11
  - pyvista=0.45.2
  - qhull=2020.2
  - qt-main=5.15.15
  - qt6-main=6.9.1
  - readline=8.2
  - scooby=0.10.1
  - setuptools=69.5.1
  - sip=6.12.0
  - snappy=1.2.1
  - sqlite=3.50.2
  - tbb=2022.1.0
  - tbb-devel=2022.1.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.2.1
  - traits=7.0.2
  - traitsui=8.0.0
  - typing-extensions=4.14.0
  - typing_extensions=4.14.0
  - unicodedata2=16.0.0
  - utfcpp=4.0.6
  - vtk-base=9.4.2
  - wheel=0.43.0
  - wslink=2.3.4
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yarl=1.20.1
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - aioitertools==0.11.0
      - alabaster==0.7.16
      - annotated-types==0.7.0
      - anyio==4.4.0
      - app-model==0.3.2
      - appdirs==1.4.4
      - appnope==0.1.4
      - arrow==1.3.0
      - attrs==23.2.0
      - babel==2.15.0
      - bcrypt==4.1.3
      - beautifulsoup4==4.12.3
      - bermuda==0.1.5
      - bibtexparser==1.4.1
      - boto3==1.34.136
      - botocore==1.34.136
      - branca==0.7.2
      - bs4==0.0.2
      - build==1.2.2.post1
      - cachey==0.2.1
      - certifi==2024.6.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - citation-map==3.12
      - click==8.1.8
      - cloudpickle==3.1.1
      - cmake==3.31.6
      - contourpy==1.2.1
      - crc32c==2.7.1
      - cryptography==42.0.8
      - dask==2025.5.1
      - debugpy==1.8.14
      - deprecated==1.2.14
      - derivative==0.6.3
      - dnspython==2.6.1
      - docstring-parser==0.16
      - docutils==0.20.1
      - donfig==0.8.1.post1
      - emmet-core==0.84.1
      - fake-useragent==1.5.1
      - farama-notifications==0.0.4
      - filelock==3.18.0
      - flexcache==0.3
      - flexparser==0.4
      - folium==0.17.0
      - fonttools==4.51.0
      - free-proxy==1.1.1
      - freetype-py==2.5.1
      - fsspec==2024.5.0
      - gdspy==1.6.13
      - geographiclib==2.0
      - geopy==2.4.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - gymnasium==1.2.2
      - h11==0.14.0
      - h5py==3.11.0
      - heapdict==1.0.1
      - hsluv==5.0.4
      - httpcore==1.0.5
      - httpx==0.27.0
      - idna==3.7
      - imageio==2.37.0
      - imagesize==1.4.1
      - importlib-metadata==8.6.1
      - in-n-out==0.2.1
      - inflect==7.3.1
      - ipykernel==6.29.5
      - jax==0.4.30
      - jax-cfd==0.2.1
      - jaxlib==0.4.30
      - jinja2==3.1.4
      - jmespath==1.0.1
      - joblib==1.4.2
      - jsonlines==4.0.0
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - juliacall==0.9.24
      - juliapkg==0.1.16
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - kiwisolver==1.4.5
      - latexcodec==3.0.0
      - lazy-loader==0.4
      - llvmlite==0.43.0
      - locket==1.0.0
      - lxml==5.2.2
      - maggma==0.68.6
      - magicgui==0.10.1
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matminer==0.9.2
      - matplotlib==3.7.3
      - mdurl==0.1.2
      - ml-dtypes==0.4.0
      - mongomock==4.1.2
      - monty==2024.5.24
      - mp-api==0.41.2
      - msgpack==1.0.8
      - napari==0.6.1
      - napari-console==0.1.3
      - napari-plugin-engine==0.2.0
      - napari-plugin-manager==0.1.6
      - napari-svg==0.2.1
      - nest-asyncio==1.6.0
      - networkx==3.3
      - npe2==0.7.8
      - numba==0.60.0
      - numcodecs==0.16.1
      - numpy==1.26.4
      - numpydoc==1.9.0
      - opencv-python==4.12.0.88
      - opt-einsum==3.3.0
      - orjson==3.10.5
      - outcome==1.3.0.post0
      - packaging==24.0
      - palettable==3.3.3
      - pandas==2.2.2
      - paramiko==3.4.0
      - partd==1.4.2
      - pint==0.24.4
      - platformdirs==4.3.7
      - plotly==5.22.0
      - powerlaw==1.5
      - protobuf==6.33.2
      - psutil==7.0.0
      - psygnal==0.13.0
      - pubchempy==1.0.4
      - pybtex==0.24.0
      - pyconify==0.2.1
      - pycountry==24.6.1
      - pydantic==2.7.4
      - pydantic-compat==0.1.2
      - pydantic-core==2.18.4
      - pydantic-settings==2.3.4
      - pydash==8.0.1
      - pymatgen==2024.4.13
      - pymongo==4.8.0
      - pynacl==1.5.0
      - pynndescent==0.5.13
      - pyopengl==3.1.9
      - pyparsing==3.1.2
      - pyproject-hooks==1.2.0
      - pyqt5-qt5==5.15.17
      - pyqt5-sip==12.17.0
      - pysindy==1.7.5
      - pysr==1.5.2
      - python-dotenv==1.0.1
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - qtconsole==5.6.1
      - qtpy==2.4.3
      - referencing==0.35.1
      - requests==2.32.3
      - rich==14.0.0
      - robocrys==0.2.9
      - rpds-py==0.18.1
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.8
      - s3transfer==0.10.2
      - safetensors==0.6.2
      - scholarly==1.7.11
      - scikit-image==0.25.2
      - scikit-learn==1.5.1
      - scs==3.2.7.post2
      - seaborn==0.13.2
      - selenium==4.23.1
      - semver==3.0.4
      - sentinels==1.0.0
      - sentry-sdk==2.47.0
      - shellingham==1.5.4
      - six==1.16.0
      - smart-open==7.0.4
      - smmap==5.0.2
      - sniffio==1.3.1
      - snowballstemmer==2.2.0
      - sortedcontainers==2.4.0
      - soupsieve==2.5
      - spglib==2.4.0
      - sphinx==7.4.7
      - sphinx-rtd-theme==2.0.0
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - sshtunnel==0.4.0
      - stable-baselines3==2.7.1
      - superqt==0.7.5
      - sympy==1.14.0
      - tabulate==0.9.0
      - tenacity==8.4.1
      - threadpoolctl==3.5.0
      - tifffile==2025.3.13
      - toolz==1.0.0
      - torch==2.3.0
      - torchaudio==2.3.0
      - torchvision==0.18.0
      - tornado==6.5.1
      - tree-math==0.2.1
      - triangle==20250106
      - trio==0.26.0
      - trio-websocket==0.11.1
      - typeguard==4.3.0
      - typer==0.16.0
      - types-python-dateutil==2.9.0.20240316
      - tzdata==2024.1
      - umap==0.1.1
      - umap-learn==0.5.7
      - uncertainties==3.2.1
      - urllib3==2.2.2
      - vispy==0.15.2
      - wandb==0.23.1
      - websocket-client==1.8.0
      - weightwatcher==0.7.5.5
      - wrapt==1.16.0
      - wsproto==1.2.0
      - xarray==2024.6.0
      - xyzservices==2024.6.0
      - zarr==3.0.8
      - zipp==3.21.0
prefix: /opt/anaconda3/envs/mag_torch
